name: Android Emulator CI for Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # ✅ changed from macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-options: "-no-audio -no-window -gpu swiftshader_indirect"
          disable-animations: true
          script: |
            adb wait-for-device
            adb shell getprop sys.boot_completed | grep -m 1 '1'
            adb install path/to/your_game.apk
            adb shell am start -n com.your.game/.MainActivity
            adb logcat -d > logcat_output.txt
