name: Android Emulator with Logcat

on:
  workflow_dispatch:

jobs:
  emulator-job:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      # Initial setup steps remain the same...
      - name: Cleanup previous runs
        run: |
          pkill -f "emulator" || true
          rm -rf "${{ runner.temp }}/android-sdk" "${{ runner.temp }}/android-avd"

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=${{ runner.temp }}/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=${{ runner.temp }}/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_AVD_HOME=${{ runner.temp }}/android-avd" >> $GITHUB_ENV
          mkdir -p "${{ runner.temp }}/android-avd"

      - name: Install Android SDK
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          curl -fo commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-mac-10406996_latest.zip
          unzip -q commandlinetools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools/"* "$ANDROID_SDK_ROOT/cmdline-tools/latest/"
          rm commandlinetools.zip
          echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Install packages (with verification)
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "emulator" "system-images;android-33;google_apis_playstore;arm64-v8a"
          
          # DEBUG: Verify system images
          echo "=== System Images Verification ==="
          ls -la "$ANDROID_SDK_ROOT/system-images/android-33/google_apis_playstore/arm64-v8a/"
          echo "=== Installed Packages ==="
          sdkmanager --list

      - name: Create AVD (with debug output)
        run: |
          echo "=== Creating AVD ==="
          echo "no" | avdmanager create avd \
            -n testEmulator \
            -k "system-images;android-33;google_apis_playstore;arm64-v8a" \
            -d pixel \
            -c 2048M

          # DEBUG: Verify AVD files
          echo "=== AVD Directory Contents ==="
          ls -la "$ANDROID_AVD_HOME/testEmulator.avd/"

          # Configure AVD
          cat <<EOF >> "$ANDROID_AVD_HOME/testEmulator.avd/config.ini"
          image.sysdir.1=system-images/android-33/google_apis_playstore/arm64-v8a/
          hw.gpu.enabled=yes
          hw.gpu.mode=swiftshader_indirect
          showDeviceFrame=no
          hw.ramSize=2048
          vm.heapSize=256
          disk.dataPartition.size=2G
          EOF

          # DEBUG: Verify config
          echo "=== Final AVD Config ==="
          cat "$ANDROID_AVD_HOME/testEmulator.avd/config.ini"

      - name: Start Emulator (with process tracking)
        run: |
          echo "=== Starting Emulator ==="
          $ANDROID_SDK_ROOT/emulator/emulator \
            -avd testEmulator \
            -no-audio \
            -no-window \
            -gpu swiftshader_indirect \
            -no-snapshot \
            -verbose > emulator.log 2>&1 &
          EMULATOR_PID=$!
          echo "EMULATOR_PID=$EMULATOR_PID" >> $GITHUB_ENV
          
          # DEBUG: Verify process
          echo "=== Running Processes ==="
          ps -ef | grep emulator || true
          echo "=== Emulator Log Head ==="
          head -20 emulator.log

      - name: Wait for boot (with robust checks)
        timeout-minutes: 10
        run: |
          echo "=== Waiting for Boot ==="
          adb start-server
          
          # Phase 1: Wait for device connection
          for i in {1..30}; do
            if adb devices | grep -q emulator; then
              echo "✅ Device detected"
              break
            fi
            echo "Waiting for device ($i/30)..."
            sleep 5
          done
          
          # Phase 2: Wait for full boot
          for i in {1..30}; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null || echo "")
            bootanim=$(adb shell getprop init.svc.bootanim 2>/dev/null || echo "running")
            
            if [[ "$boot_completed" == "1" && "$bootanim" == "stopped" ]]; then
              echo "✅ Fully booted!"
              adb shell input keyevent 82
              exit 0
            fi
            
            # DEBUG: Additional checks
            echo "Status ($i/30): boot_completed=$boot_completed, bootanim=$bootanim"
            echo "=== ADB Devices ==="
            adb devices -l
            sleep 5
          done
          
          # DEBUG: Failure investigation
          echo "❌ Boot failed!"
          echo "=== Last 50 Log Lines ==="
          tail -50 emulator.log
          echo "=== ADB Properties ==="
          adb shell getprop || true
          exit 1

      - name: Capture Logs
        if: always()
        run: |
          echo "=== Final Debug Info ==="
          echo "--- Processes ---"
          ps -ef | grep -E 'emulator|adb' || true
          echo "--- ADB Devices ---"
          adb devices -l || true
          echo "--- System Properties ---"
          adb shell getprop || true
          
          # Save logs
          adb logcat -d > logcat.txt || true
          tail -100 emulator.log > emulator-tail.log

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: emulator-logs
          path: |
            logcat.txt
            emulator.log
            emulator-tail.log
