name: Android Emulator CI for Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.6

      - name: Start Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: arm64-v8a
          profile: Nexus 6
          emulator-options: "-no-audio" # remove -no-window if you want full GUI
          disable-animations: true
          script: |
            adb install path/to/your_game.apk
            adb shell am start -n com.your.game/.MainActivity
            adb logcat -d > logcat_output.txt
