name: Android ARM64 Emulator on macOS

on:
  workflow_dispatch:

jobs:
  android-emulator:
    runs-on: macos-latest
    steps:
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "system-images;android-34;default;arm64-v8a" "emulator"

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd -n Pixel_ARM -k "system-images;android-34;default;arm64-v8a" -d pixel

      - name: Launch Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd Pixel_ARM -no-window -no-audio -no-snapshot &
          adb wait-for-device
          adb shell getprop ro.product.cpu.abi

      - name: Run Your APK or Test Commands
        run: |
          adb install your-app.apk
          adb shell am start -n com.yourcompany.yourgame/.MainActivity
          adb logcat -d | tee logcat.txt
