name: Android Emulator Logcat

on:
  workflow_dispatch:

jobs:
  emulator-logcat:
    runs-on: windows-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}\android-sdk
      ANDROID_HOME: ${{ github.workspace }}\android-sdk
      EMULATOR_NAME: test-emulator

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "ANDROID_SDK_ROOT=${{ env.ANDROID_SDK_ROOT }}" >> $env:GITHUB_ENV
          echo "ANDROID_HOME=${{ env.ANDROID_HOME }}" >> $env:GITHUB_ENV

      - name: Download Android SDK command line tools
        run: |
          Invoke-WebRequest https://dl.google.com/android/repository/commandlinetools-win-9477386_latest.zip -OutFile cmdline-tools.zip
          Expand-Archive cmdline-tools.zip -DestinationPath "$env:ANDROID_SDK_ROOT\temp"
          mkdir "$env:ANDROID_SDK_ROOT\cmdline-tools\latest" -Force
          Move-Item "$env:ANDROID_SDK_ROOT\temp\cmdline-tools\*" "$env:ANDROID_SDK_ROOT\cmdline-tools\latest"
          Remove-Item -Recurse -Force "$env:ANDROID_SDK_ROOT\temp"
        shell: pwsh

      - name: Add SDK tools to PATH
        run: |
          echo "$env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin" >> $env:GITHUB_PATH
          echo "$env:ANDROID_SDK_ROOT\platform-tools" >> $env:GITHUB_PATH
          echo "$env:ANDROID_SDK_ROOT\emulator" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Accept Android SDK licenses
        run: |
          mkdir -p "$env:ANDROID_SDK_ROOT\licenses"
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$env:ANDROID_SDK_ROOT\licenses\android-sdk-license"
          echo "84831b9409646a918e30573bab4c9c91346d8abd" > "$env:ANDROID_SDK_ROOT\licenses\android-sdk-preview-license"
        shell: pwsh

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install required Android SDK components
        run: |
          $ErrorActionPreference = "Stop"
          & "$env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin\sdkmanager.bat" --sdk_root="$env:ANDROID_SDK_ROOT" "platform-tools" "emulator" "system-images;android-30;google_apis;x86_64"
          & "$env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin\sdkmanager.bat" --licenses --sdk_root="$env:ANDROID_SDK_ROOT"
        shell: pwsh

      - name: List installed SDK components
        run: |
          & "$env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin\sdkmanager.bat" --list_installed --sdk_root="$env:ANDROID_SDK_ROOT"
        shell: pwsh

      - name: Create Emulator
        run: |
          echo no | & "$env:ANDROID_SDK_ROOT\cmdline-tools\latest\bin\avdmanager.bat" create avd -n $env:EMULATOR_NAME -k "system-images;android-30;google_apis;x86_64" --force --device "pixel"
        shell: pwsh

      - name: Start Emulator
        run: |
          # Start emulator in background
          $emulatorProcess = Start-Process -PassThru -FilePath "$env:ANDROID_SDK_ROOT\emulator\emulator.exe" -ArgumentList "-avd $env:EMULATOR_NAME -memory 2048 -cores 2 -no-snapshot -no-audio -gpu swiftshader_indirect -no-boot-anim -verbose"
          
          # Wait for device to be ready
          $attempts = 0
          $maxAttempts = 30
          $isBooted = $false
          
          Write-Host "Waiting for emulator to boot..."
          
          while (($attempts -lt $maxAttempts) -and (-not $isBooted)) {
              try {
                  $bootStatus = adb shell getprop sys.boot_completed 2>&1
                  if ($bootStatus -eq "1") {
                      $isBooted = $true
                      Write-Host "Emulator booted successfully!"
                      break
                  }
              } catch {
                  # Ignore errors while waiting
              }
              
              $attempts++
              Start-Sleep -Seconds 10
          }
          
          if (-not $isBooted) {
              Write-Host "Emulator failed to boot within the allotted time"
              $emulatorProcess | Stop-Process -Force
              exit 1
          }
        shell: pwsh

      - name: Check device status
        run: |
          adb devices
          adb shell getprop
        shell: pwsh

      - name: Logcat Output
        run: |
          adb logcat -d > logcat_output.txt
          Get-Content logcat_output.txt
        shell: pwsh

      - name: Upload Logcat Output
        uses: actions/upload-artifact@v4
        with:
          name: logcat-output
          path: logcat_output.txt
