name: Android Emulator Logcat Capture

on:
  workflow_dispatch:

jobs:
  emulator-logcat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Enable KVM for hardware acceleration
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo adduser $USER libvirt
          sudo adduser $USER kvm
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run emulator and capture Logcat
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.6
        with:
          api: 30
          tag: google_apis
          abi: x86
          disable-animations: true
          boot-timeout: 600
          verbose: true
          cmd: |
            echo "Starting Logcat capture..."
            adb logcat -c
            adb logcat -v time > artifacts/logcat.log &
            echo "Logcat is running in the background."
            sleep 30
            echo "Stopping Logcat capture."
            pkill -f "adb logcat"

      - name: Upload Logcat output
        uses: actions/upload-artifact@v4
        with:
          name: logcat
          path: artifacts/logcat.log
